org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47.1.3,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=cam
mod_name=Create: Alex's Mobs
mod_license=Apache-2.0
mod_version=1.3.1
mod_group_id=com.erju312.cam
mod_authors=erju312
mod_description=Integrates Alex's Mobs into Create's automation systems.
mod_url=https://github.com/erju312/Create-Alexs-Mobs
mod_issue_tracker=https://github.com/erju312/Create-Alexs-Mobs/issues
